[package]
name = "jeriya_test"
version = "0.4.0"
edition = "2021"

[dependencies]
jeriya_shared = { path = "../jeriya_shared" }
chrono = "0.4.24"
image = "0.24.5"
image-compare = "0.2.4"
simple_logger = "4.2.0"
